/**
 * PLAN.md — a *view* of the relay plan, not a second source of truth.
 *
 * The relay plan is versioned, per-member approved, lockable, and consent binds
 * a signature to its exact hash. A parallel freeform file would let the document
 * people read drift from the one they signed, so this module only renders the
 * relay plan out and parses edits back in for `/propose`.
 */

export type ItemStatus = "pending" | "in_progress" | "done";

export interface PlanItemView {
  owner: string;
  task: string;
  status: ItemStatus;
  dependsOn?: number[];
}

export interface PlanView {
  goal: string;
  items: PlanItemView[];
  version: number;
  locked: boolean;
  /** Agent ids that have approved the current version. */
  approvedBy: string[];
}

/** agentId → handle written into the file, e.g. `you`, `krishay`. */
export type Handles = Record<string, string>;

const HEADER = "PLAN.md  (generated by inzo — edit freely, /propose to publish)";
const MARK: Record<ItemStatus, string> = { pending: " ", in_progress: ">", done: "x" };

export function render(plan: PlanView, handles: Handles): string {
  const handle = (agentId: string) => handles[agentId] ?? agentId;
  const width = Math.max(0, ...plan.items.map((item) => handle(item.owner).length + 1));

  const tasks = plan.items.map((item) => {
    const owner = `@${handle(item.owner)}`.padEnd(width + 1);
    // Displayed 1-based: the file is for humans, dependsOn is for the relay.
    const needs = item.dependsOn?.length ? `   (needs: ${item.dependsOn.map((i) => i + 1).join(", ")})` : "";
    return `- [${MARK[item.status]}] ${owner} ${item.task}${needs}`;
  });

  const footer = [
    `version ${plan.version}`,
    plan.locked ? "locked" : "open",
    `approved ${plan.approvedBy.map(handle).join(",") || "none"}`,
  ].join(" | ");

  return [HEADER, "", "# Goal", plan.goal, "", "## Tasks", ...tasks, "", `<!-- inzo: ${footer} -->`, ""].join("\n");
}

export class PlanFileError extends Error {}

export function parse(text: string, handles: Handles): PlanView {
  const byHandle = new Map(Object.entries(handles).map(([agentId, name]) => [name, agentId]));
  const lines = text.split("\n");

  const goalAt = lines.findIndex((line) => line.trim() === "# Goal");
  const tasksAt = lines.findIndex((line) => line.trim() === "## Tasks");
  if (goalAt === -1 || tasksAt === -1 || tasksAt < goalAt) {
    throw new PlanFileError("PLAN.md needs a `# Goal` section followed by a `## Tasks` section.");
  }

  const goal = lines
    .slice(goalAt + 1, tasksAt)
    .map((line) => line.trim())
    .filter(Boolean)
    .join(" ");
  if (!goal) throw new PlanFileError("The `# Goal` section is empty.");

  const items: PlanItemView[] = [];
  for (const line of lines.slice(tasksAt + 1)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("<!--")) continue;
    const match = trimmed.match(/^- \[(.)\]\s+@(\S+)\s+(.*)$/);
    if (!match) throw new PlanFileError(`Cannot parse task line: ${trimmed}`);

    const [, mark, handle, rest] = match;
    const status = (Object.keys(MARK) as ItemStatus[]).find((key) => MARK[key] === (mark === "" ? " " : mark));
    if (!status) throw new PlanFileError(`Unknown status "[${mark}]" — use [ ], [>] or [x].`);

    const needsMatch = rest.match(/\(needs:\s*([\d,\s]+)\)\s*$/);
    const task = (needsMatch ? rest.slice(0, needsMatch.index) : rest).trim();
    if (!task) throw new PlanFileError(`Task line has no task text: ${trimmed}`);

    const dependsOn = needsMatch
      ? needsMatch[1]
          .split(",")
          .map((part) => Number(part.trim()) - 1)
          .filter((index) => !Number.isNaN(index))
      : undefined;

    // A dependency must point at an earlier item. That single rule makes a
    // cycle syntactically impossible — no graph traversal needed to reject one.
    for (const index of dependsOn ?? []) {
      if (index < 0 || index >= items.length) {
        throw new PlanFileError(
          `Task ${items.length + 1} depends on task ${index + 1}, which must be an earlier task in the list.`,
        );
      }
    }

    items.push({
      owner: byHandle.get(handle) ?? handle,
      task,
      status,
      ...(dependsOn?.length ? { dependsOn } : {}),
    });
  }

  if (items.length === 0) throw new PlanFileError("The `## Tasks` section has no tasks.");

  const footer = text.match(/<!--\s*inzo:\s*version (\d+)\s*\|\s*(locked|open)\s*\|\s*approved ([^>]*?)\s*-->/);
  const approvedNames = footer ? footer[3].split(",").map((name) => name.trim()).filter((name) => name && name !== "none") : [];

  return {
    goal,
    items,
    version: footer ? Number(footer[1]) : 0,
    locked: footer ? footer[2] === "locked" : false,
    approvedBy: approvedNames.map((name) => byHandle.get(name) ?? name),
  };
}
